# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_save'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='save',
            options={'ordering': ['-pk']},
        ),
    ]
